# Form implementation generated from reading ui file 'createProjectDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName("MainDialog")
        MainDialog.resize(400, 300)
        MainDialog.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(85, 87, 83);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainFrame = QtWidgets.QFrame(parent=MainDialog)
        self.mainFrame.setAutoFillBackground(False)
        self.mainFrame.setStyleSheet("border-color: rgb(85, 87, 83);")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setLineWidth(1)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nameLbl = QtWidgets.QLabel(parent=self.mainFrame)
        self.nameLbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nameLbl.setObjectName("nameLbl")
        self.verticalLayout_2.addWidget(self.nameLbl)
        self.nameInput = QtWidgets.QLineEdit(parent=self.mainFrame)
        self.nameInput.setText("")
        self.nameInput.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.nameInput.setPlaceholderText("")
        self.nameInput.setObjectName("nameInput")
        self.verticalLayout_2.addWidget(self.nameInput)
        self.imageDirLbl = QtWidgets.QLabel(parent=self.mainFrame)
        self.imageDirLbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.imageDirLbl.setObjectName("imageDirLbl")
        self.verticalLayout_2.addWidget(self.imageDirLbl)
        self.inputFrame = QtWidgets.QFrame(parent=self.mainFrame)
        self.inputFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.inputFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.inputFrame.setObjectName("inputFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.inputFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageDirInput = QtWidgets.QLineEdit(parent=self.inputFrame)
        self.imageDirInput.setClearButtonEnabled(False)
        self.imageDirInput.setObjectName("imageDirInput")
        self.horizontalLayout_2.addWidget(self.imageDirInput)
        self.dirSearchBtn = QtWidgets.QPushButton(parent=self.inputFrame)
        self.dirSearchBtn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.dirSearchBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icons8-ellipsis-20.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.dirSearchBtn.setIcon(icon)
        self.dirSearchBtn.setObjectName("dirSearchBtn")
        self.horizontalLayout_2.addWidget(self.dirSearchBtn)
        self.verticalLayout_2.addWidget(self.inputFrame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.confirmBtn = QtWidgets.QPushButton(parent=self.mainFrame)
        self.confirmBtn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.confirmBtn.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.confirmBtn.setAutoDefault(False)
        self.confirmBtn.setObjectName("confirmBtn")
        self.verticalLayout_2.addWidget(self.confirmBtn)
        self.horizontalLayout.addWidget(self.mainFrame)

        self.retranslateUi(MainDialog)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)

    def retranslateUi(self, MainDialog):
        _translate = QtCore.QCoreApplication.translate
        MainDialog.setWindowTitle(_translate("MainDialog", "Create a new Project"))
        self.nameLbl.setText(_translate("MainDialog", "Project Name"))
        self.imageDirLbl.setText(_translate("MainDialog", "Image Directory"))
        self.confirmBtn.setText(_translate("MainDialog", "Ok"))
