# Form implementation generated from reading ui file 'createClassDialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_createClassDialog(object):
    def setupUi(self, createClassDialog):
        createClassDialog.setObjectName("createClassDialog")
        createClassDialog.resize(400, 160)
        createClassDialog.setMaximumSize(QtCore.QSize(400, 160))
        createClassDialog.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"border : 1px solid;\n"
"border-radius: 5px;\n"
"border-color:  rgb(85, 87, 83);")
        self.verticalLayout = QtWidgets.QVBoxLayout(createClassDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainFrame = QtWidgets.QFrame(parent=createClassDialog)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.classNameFrame = QtWidgets.QFrame(parent=self.mainFrame)
        self.classNameFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.classNameFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.classNameFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.classNameFrame.setObjectName("classNameFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.classNameFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.classNameLbl = QtWidgets.QLabel(parent=self.classNameFrame)
        self.classNameLbl.setMaximumSize(QtCore.QSize(110, 16777215))
        self.classNameLbl.setStyleSheet("font: 75 12pt \"Gotham Rounded\";\n"
"color: rgb(255, 255, 255);")
        self.classNameLbl.setObjectName("classNameLbl")
        self.horizontalLayout.addWidget(self.classNameLbl)
        self.classNameLineEdit = QtWidgets.QLineEdit(parent=self.classNameFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classNameLineEdit.sizePolicy().hasHeightForWidth())
        self.classNameLineEdit.setSizePolicy(sizePolicy)
        self.classNameLineEdit.setMaximumSize(QtCore.QSize(250, 30))
        self.classNameLineEdit.setStyleSheet("background-color: rgb(65, 66, 64);\n"
"color: rgb(255, 255, 255);")
        self.classNameLineEdit.setObjectName("classNameLineEdit")
        self.horizontalLayout.addWidget(self.classNameLineEdit)
        self.verticalLayout_2.addWidget(self.classNameFrame)
        self.classColourFrame = QtWidgets.QFrame(parent=self.mainFrame)
        self.classColourFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.classColourFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.classColourFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.classColourFrame.setObjectName("classColourFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.classColourFrame)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.classColourLbl = QtWidgets.QLabel(parent=self.classColourFrame)
        self.classColourLbl.setMaximumSize(QtCore.QSize(110, 60))
        self.classColourLbl.setStyleSheet("font: 75 12pt \"Gotham Rounded\";\n"
"color: rgb(255, 255, 255);")
        self.classColourLbl.setObjectName("classColourLbl")
        self.horizontalLayout_2.addWidget(self.classColourLbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.classColourBtn = QtWidgets.QPushButton(parent=self.classColourFrame)
        self.classColourBtn.setMaximumSize(QtCore.QSize(20, 20))
        self.classColourBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.classColourBtn.setStyleSheet("border-radius: 4px;\n"
"background-color: rgb(138, 226, 52);\n"
"border: 3px solid rgb(105, 105, 105);")
        self.classColourBtn.setText("")
        self.classColourBtn.setObjectName("classColourBtn")
        self.horizontalLayout_2.addWidget(self.classColourBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.classColourFrame)
        self.createFrame = QtWidgets.QFrame(parent=self.mainFrame)
        self.createFrame.setMinimumSize(QtCore.QSize(0, 30))
        self.createFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.createFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.createFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.createFrame.setObjectName("createFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.createFrame)
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.createClassBtn = QtWidgets.QPushButton(parent=self.createFrame)
        self.createClassBtn.setMinimumSize(QtCore.QSize(110, 30))
        self.createClassBtn.setMaximumSize(QtCore.QSize(110, 16777215))
        self.createClassBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.createClassBtn.setStyleSheet("background-color: rgb(65, 66, 64);\n"
"border : 1px solid;\n"
"border-radius: 10px;\n"
"border-color:  rgb(85, 87, 83);\n"
"font: 75 bold 12pt \"Gotham Rounded\";\n"
"color: rgb(255, 255, 255);")
        self.createClassBtn.setObjectName("createClassBtn")
        self.horizontalLayout_3.addWidget(self.createClassBtn)
        spacerItem3 = QtWidgets.QSpacerItem(107, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.createFrame)
        self.verticalLayout.addWidget(self.mainFrame)

        self.retranslateUi(createClassDialog)
        QtCore.QMetaObject.connectSlotsByName(createClassDialog)

    def retranslateUi(self, createClassDialog):
        _translate = QtCore.QCoreApplication.translate
        createClassDialog.setWindowTitle(_translate("createClassDialog", "Dialog"))
        self.classNameLbl.setText(_translate("createClassDialog", "Class Name:"))
        self.classColourLbl.setText(_translate("createClassDialog", "Class Colour:"))
        self.createClassBtn.setText(_translate("createClassDialog", "Create"))
