# Form implementation generated from reading ui file 'notificationManager.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName("MainDialog")
        MainDialog.setEnabled(True)
        MainDialog.resize(500, 50)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainDialog.sizePolicy().hasHeightForWidth())
        MainDialog.setSizePolicy(sizePolicy)
        MainDialog.setMinimumSize(QtCore.QSize(500, 50))
        MainDialog.setMaximumSize(QtCore.QSize(500, 400))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        MainDialog.setFont(font)
        MainDialog.setWindowTitle("")
        MainDialog.setWindowOpacity(1.0)
        MainDialog.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"border-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(MainDialog)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainFrame = QtWidgets.QFrame(parent=MainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        self.mainFrame.setMinimumSize(QtCore.QSize(0, 30))
        self.mainFrame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.mainFrame.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);\n"
"border : 1px solid; \n"
"border-color: rgb(85, 87, 83);")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.notificationLbl = QtWidgets.QLabel(parent=self.mainFrame)
        self.notificationLbl.setStyleSheet("color: rgb(186, 189, 182);\n"
"font: 75 bold 10pt \"Gotham Rounded\";")
        self.notificationLbl.setObjectName("notificationLbl")
        self.horizontalLayout_2.addWidget(self.notificationLbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.doNotDisturbBtn = QtWidgets.QPushButton(parent=self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doNotDisturbBtn.sizePolicy().hasHeightForWidth())
        self.doNotDisturbBtn.setSizePolicy(sizePolicy)
        self.doNotDisturbBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.doNotDisturbBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icons8-notification-bell-30-inactive.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("icons/icons8-do-not-disturb-30.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.doNotDisturbBtn.setIcon(icon)
        self.doNotDisturbBtn.setIconSize(QtCore.QSize(20, 20))
        self.doNotDisturbBtn.setCheckable(True)
        self.doNotDisturbBtn.setObjectName("doNotDisturbBtn")
        self.horizontalLayout_2.addWidget(self.doNotDisturbBtn)
        self.hideBtn = QtWidgets.QPushButton(parent=self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hideBtn.sizePolicy().hasHeightForWidth())
        self.hideBtn.setSizePolicy(sizePolicy)
        self.hideBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.hideBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/icons8-close-30.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.hideBtn.setIcon(icon1)
        self.hideBtn.setIconSize(QtCore.QSize(20, 20))
        self.hideBtn.setObjectName("hideBtn")
        self.horizontalLayout_2.addWidget(self.hideBtn)
        self.verticalLayout.addWidget(self.mainFrame)
        self.notificationListWidget = QtWidgets.QListWidget(parent=MainDialog)
        self.notificationListWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notificationListWidget.sizePolicy().hasHeightForWidth())
        self.notificationListWidget.setSizePolicy(sizePolicy)
        self.notificationListWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.notificationListWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        self.notificationListWidget.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(255, 255, 255);\n"
"border : 1px solid; \n"
"border-color: rgb(85, 87, 83);")
        self.notificationListWidget.setObjectName("notificationListWidget")
        self.verticalLayout.addWidget(self.notificationListWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(MainDialog)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)

    def retranslateUi(self, MainDialog):
        _translate = QtCore.QCoreApplication.translate
        self.notificationLbl.setText(_translate("MainDialog", "NO NEW NOTIFICATIONS"))
