# Form implementation generated from reading ui file 'annotationManagerUtilityFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_annotationManagerUtilityFrame(object):
    def setupUi(self, annotationManagerUtilityFrame):
        annotationManagerUtilityFrame.setObjectName("annotationManagerUtilityFrame")
        annotationManagerUtilityFrame.resize(463, 30)
        annotationManagerUtilityFrame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.horizontalLayout = QtWidgets.QHBoxLayout(annotationManagerUtilityFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.classSearchLineEdit = QtWidgets.QLineEdit(parent=annotationManagerUtilityFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classSearchLineEdit.sizePolicy().hasHeightForWidth())
        self.classSearchLineEdit.setSizePolicy(sizePolicy)
        self.classSearchLineEdit.setPlaceholderText("")
        self.classSearchLineEdit.setObjectName("classSearchLineEdit")
        self.horizontalLayout.addWidget(self.classSearchLineEdit)
        self.annoManagerCreateClassBtn = QtWidgets.QPushButton(parent=annotationManagerUtilityFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annoManagerCreateClassBtn.sizePolicy().hasHeightForWidth())
        self.annoManagerCreateClassBtn.setSizePolicy(sizePolicy)
        self.annoManagerCreateClassBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.annoManagerCreateClassBtn.setObjectName("annoManagerCreateClassBtn")
        self.horizontalLayout.addWidget(self.annoManagerCreateClassBtn)

        self.retranslateUi(annotationManagerUtilityFrame)
        QtCore.QMetaObject.connectSlotsByName(annotationManagerUtilityFrame)

    def retranslateUi(self, annotationManagerUtilityFrame):
        _translate = QtCore.QCoreApplication.translate
        annotationManagerUtilityFrame.setWindowTitle(_translate("annotationManagerUtilityFrame", "Frame"))
        self.annoManagerCreateClassBtn.setText(_translate("annotationManagerUtilityFrame", "+ Class"))
