# Form implementation generated from reading ui file 'annotationManager.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_annotationManagerFrame(object):
    def setupUi(self, annotationManagerFrame):
        annotationManagerFrame.setObjectName("annotationManagerFrame")
        annotationManagerFrame.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(annotationManagerFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.utilityFrame = QtWidgets.QFrame(parent=annotationManagerFrame)
        self.utilityFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.utilityFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.utilityFrame.setObjectName("utilityFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.utilityFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.classSearchLineEdit = QtWidgets.QLineEdit(parent=self.utilityFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classSearchLineEdit.sizePolicy().hasHeightForWidth())
        self.classSearchLineEdit.setSizePolicy(sizePolicy)
        self.classSearchLineEdit.setPlaceholderText("")
        self.classSearchLineEdit.setObjectName("classSearchLineEdit")
        self.horizontalLayout.addWidget(self.classSearchLineEdit)
        self.annoManagerCreateClassBtn = QtWidgets.QPushButton(parent=self.utilityFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annoManagerCreateClassBtn.sizePolicy().hasHeightForWidth())
        self.annoManagerCreateClassBtn.setSizePolicy(sizePolicy)
        self.annoManagerCreateClassBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.annoManagerCreateClassBtn.setObjectName("annoManagerCreateClassBtn")
        self.horizontalLayout.addWidget(self.annoManagerCreateClassBtn)
        self.verticalLayout.addWidget(self.utilityFrame)
        self.classSelectionFrame = QtWidgets.QFrame(parent=annotationManagerFrame)
        self.classSelectionFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.classSelectionFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.classSelectionFrame.setObjectName("classSelectionFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.classSelectionFrame)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.classSelectionTreeWidget = QtWidgets.QTreeWidget(parent=self.classSelectionFrame)
        self.classSelectionTreeWidget.setIndentation(0)
        self.classSelectionTreeWidget.setHeaderHidden(True)
        self.classSelectionTreeWidget.setExpandsOnDoubleClick(False)
        self.classSelectionTreeWidget.setObjectName("classSelectionTreeWidget")
        self.classSelectionTreeWidget.headerItem().setText(0, "1")
        self.classSelectionTreeWidget.header().setMinimumSectionSize(0)
        self.verticalLayout_2.addWidget(self.classSelectionTreeWidget)
        self.verticalLayout.addWidget(self.classSelectionFrame)

        self.retranslateUi(annotationManagerFrame)
        QtCore.QMetaObject.connectSlotsByName(annotationManagerFrame)

    def retranslateUi(self, annotationManagerFrame):
        _translate = QtCore.QCoreApplication.translate
        annotationManagerFrame.setWindowTitle(_translate("annotationManagerFrame", "Frame"))
        self.annoManagerCreateClassBtn.setText(_translate("annotationManagerFrame", "+ Class"))
