# Form implementation generated from reading ui file 'annotationManagerClassSelectionFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_annotationManagerUtilityFrame(object):
    def setupUi(self, annotationManagerUtilityFrame):
        annotationManagerUtilityFrame.setObjectName("annotationManagerUtilityFrame")
        annotationManagerUtilityFrame.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(annotationManagerUtilityFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.classSelectionTreeWidget = QtWidgets.QTreeWidget(parent=annotationManagerUtilityFrame)
        self.classSelectionTreeWidget.setIndentation(0)
        self.classSelectionTreeWidget.setHeaderHidden(True)
        self.classSelectionTreeWidget.setObjectName("classSelectionTreeWidget")
        self.classSelectionTreeWidget.headerItem().setText(0, "1")
        self.classSelectionTreeWidget.header().setMinimumSectionSize(0)
        self.verticalLayout.addWidget(self.classSelectionTreeWidget)

        self.retranslateUi(annotationManagerUtilityFrame)
        QtCore.QMetaObject.connectSlotsByName(annotationManagerUtilityFrame)

    def retranslateUi(self, annotationManagerUtilityFrame):
        _translate = QtCore.QCoreApplication.translate
        annotationManagerUtilityFrame.setWindowTitle(_translate("annotationManagerUtilityFrame", "Frame"))
